import logging
import io
import re
import pandas as pd
from typing import Any, Dict, List, Optional, Tuple
from fastapi import APIRouter, HTTPException, UploadFile, File, status

from src.agents.rci_plan.graph import rci_plan_graph, RciPlanState
from src.agents.rci_plan.schemas import (
    RciPlanRequest,
    RciPlanResponse,
    ExcelUploadResponse,
)
from src.utils.deps import get_db_pool

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/rci", tags=["RCI Plan"])

_OBJECTIVE_PREFIX = re.compile(r'^\s*objective\s*[:/]?\s*', re.IGNORECASE)


def _split_title_and_objective(raw: str) -> Tuple[str, Optional[str]]:
    """
    Split a section title that embeds its objective as the last parenthetical.

    "Drying Parameters (FBD) (To examine why the moisture endpoint was missed)"
      → title:     "Drying Parameters (FBD)"
      → objective: "To examine why the moisture endpoint was missed"

    Rules
    -----
    - Only the LAST (...) group is treated as the objective.
    - Any earlier (...) groups stay in the title unchanged.
    - Strip a leading "Objective:" / "Objective :" prefix from the extracted text.
    - If no parenthetical exists, title is the full string and objective is None.
    """
    parens = list(re.finditer(r'\(([^)]+)\)', raw))
    if not parens:
        return raw.strip(), None

    last = parens[-1]
    objective_text = last.group(1).strip()
    objective_text = _OBJECTIVE_PREFIX.sub('', objective_text).strip()

    clean_title = (raw[:last.start()] + raw[last.end():]).strip()
    # Collapse any trailing/internal extra spaces left by removal
    clean_title = re.sub(r'\s{2,}', ' ', clean_title).strip()
    clean_title = clean_title.rstrip(") ").strip()

    return clean_title, objective_text or None


@router.post(
    "/plan",
    response_model=RciPlanResponse,
    summary="Generate RCI plan for a quality event",
)
async def generate_rci_plan(request: RciPlanRequest) -> RciPlanResponse:
    """
    Analyse a quality event and return the list of RCI sections and task items to perform.

    **Supported event types:** Deviation, OOS, OOT, OOS/OOT, Market Complaint
    """
    try:
        state = RciPlanState(
            trackwise_fields=request.trackwise_fields,
            event_type=request.event_type,
        )
        logger.info(f"Processing RCI plan generation for event_type: {request.event_type}")

        final_state = await rci_plan_graph.ainvoke(state)
        result = final_state.get("final_result")

        if not result:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Final result not generated by the graph",
            )

        return RciPlanResponse(
            event_type=result["event_type"],
            failure_type=result["failure_type"],
            archetype=result["archetype"],
            sections=result["sections"],
            total_sections_count=result["total_sections_count"],
            total_tasks_count=result["total_tasks_count"],
        )

    except Exception as e:
        logger.exception("Error in RCI plan generation")
        error_msg = str(e)
        if "Invalid trackwise fields" in error_msg or "ValidationError" in error_msg:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"Invalid trackwise fields: {error_msg}",
            )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to process RCI plan generation: {error_msg}",
        )


@router.post(
    "/upload",
    response_model=ExcelUploadResponse,
    summary="Upload an Excel file containing RCI Plan templates",
)
async def upload_rci_templates(file: UploadFile = File(...)) -> ExcelUploadResponse:
    """
    Expected Excel Structure

    Row 1:
        Confirmed Assay Failure (Level 2)

    Row 2:
        Sr.No. | RCI PLAN | Tasks | Objective / Rationale

    Row 3+:
        Data rows

    Mapping:
        Archetype Name        -> First row, first cell
        RCI PLAN             -> Section Title
        Tasks                -> Task Description
        Objective/Rationale  -> Section Correlation
    """

    filename = (file.filename or "").strip()
    suffix = filename.split(".")[-1].lower() if "." in filename else ""

    if suffix not in ["xlsx", "xls"]:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail="Only Excel (.xlsx, .xls) files are supported.",
        )

    def find_col(possible_names: List[str], df_cols: List[Any]):
        normalized = {name.strip().lower() for name in possible_names}

        for col in df_cols:
            if str(col).strip().lower() in normalized:
                return col

        return None

    try:
        contents = await file.read()

        excel_file = pd.ExcelFile(io.BytesIO(contents))

        plans_count = 0
        sections_count = 0
        tasks_count = 0
        archetypes_processed = set()

        db_pool = await get_db_pool()

        async with db_pool.acquire() as conn:
            async with conn.transaction():

                # ------------------------------------------------------------------
                # Ensure Archetype Type exists
                # ------------------------------------------------------------------
                archetype_type_row = await conn.fetchrow(
                    """
                    SELECT id
                    FROM archetype_type
                    WHERE name = $1
                    """,
                    "RCI Plan",
                )

                if archetype_type_row:
                    archetype_type_id = archetype_type_row["id"]
                else:
                    archetype_type_id = await conn.fetchval(
                        """
                        INSERT INTO archetype_type (name)
                        VALUES ($1)
                        RETURNING id
                        """,
                        "RCI Plan",
                    )

                # ------------------------------------------------------------------
                # Process each worksheet
                # ------------------------------------------------------------------
                for sheet_name in excel_file.sheet_names:

                    logger.info(f"Processing worksheet: {sheet_name}")

                    # --------------------------------------------------------------
                    # Read first row -> Archetype Name
                    # --------------------------------------------------------------
                    archetype_row = pd.read_excel(
                        excel_file,
                        sheet_name=sheet_name,
                        header=None,
                        nrows=1,
                    )

                    archetype_name = None

                    for value in archetype_row.iloc[0]:
                        if pd.notna(value):
                            archetype_name = str(value).strip()
                            break

                    if not archetype_name:
                        logger.warning(
                            f"Skipping sheet '{sheet_name}' - archetype name not found"
                        )
                        continue

                    # --------------------------------------------------------------
                    # Read actual table
                    # Header row = second row in Excel
                    # --------------------------------------------------------------
                    df = pd.read_excel(
                        excel_file,
                        sheet_name=sheet_name,
                        header=1,
                    )

                    if df.empty:
                        logger.warning(
                            f"Skipping sheet '{sheet_name}' - no data rows found"
                        )
                        continue

                    df.columns = [str(col).strip() for col in df.columns]

                    logger.info(
                        f"Sheet '{sheet_name}' columns: {list(df.columns)}"
                    )

                    section_col = find_col(
                        [
                            "rci plan",
                            "rci_plan",
                            "task(s) & objective",
                            "tasks & objective",
                            "task & objective",
                        ],
                        df.columns,
                    )

                    task_col = find_col(
                        ["task details", "tasks", "task"],
                        df.columns,
                    )

                    correlation_col = find_col(
                        [
                            "objective / rationale",
                            "objective/rationale",
                            "objective",
                            "rationale",
                        ],
                        df.columns,
                    )

                    if not section_col or not task_col:
                        logger.warning(
                            "Skipping sheet '%s' — missing required columns "
                            "(need section and task columns). Looks like an index or summary sheet.",
                            sheet_name,
                        )
                        continue

                    archetypes_processed.add(archetype_name)

                    # --------------------------------------------------------------
                    # Handle merged cells
                    # --------------------------------------------------------------
                    df[section_col] = df[section_col].ffill()

                    if correlation_col:
                        df[correlation_col] = df[correlation_col].ffill()

                    # Remove rows without tasks
                    df = df.dropna(subset=[task_col])

                    if df.empty:
                        logger.warning(
                            f"Skipping sheet '{sheet_name}' - no valid task rows"
                        )
                        continue

                    # --------------------------------------------------------------
                    # Find/Create Archetype
                    # --------------------------------------------------------------
                    archetype_row_db = await conn.fetchrow(
                        """
                        SELECT id
                        FROM archetype
                        WHERE LOWER(name) = LOWER($1) AND archetype_type_id = $2
                        LIMIT 1
                        """,
                        archetype_name,
                        archetype_type_id,
                    )

                    if archetype_row_db:
                        archetype_id = archetype_row_db["id"]
                    else:
                        archetype_id = await conn.fetchval(
                            """
                            INSERT INTO archetype
                            (
                                name,
                                archetype_type_id
                            )
                            VALUES ($1, $2)
                            RETURNING id
                            """,
                            archetype_name,
                            archetype_type_id,
                        )

                    # --------------------------------------------------------------
                    # Delete existing plan
                    # --------------------------------------------------------------
                    await conn.execute(
                        """
                        DELETE FROM rci_plan
                        WHERE archetype_id = $1
                        """,
                        archetype_id,
                    )

                    # --------------------------------------------------------------
                    # Create plan
                    # --------------------------------------------------------------
                    plan_id = await conn.fetchval(
                        """
                        INSERT INTO rci_plan
                        (
                            archetype_id
                        )
                        VALUES ($1)
                        RETURNING id
                        """,
                        archetype_id,
                    )

                    plans_count += 1

                    # --------------------------------------------------------------
                    # Group by section
                    # --------------------------------------------------------------
                    grouped_sections = df.groupby(section_col)

                    for section_title, section_group in grouped_sections:

                        section_title = str(section_title).strip()

                        if not section_title:
                            continue

                        # ── Extract objective from embedded last parenthetical ──────
                        # e.g. "Drying Parameters (FBD) (To examine why...)"
                        #   → title="Drying Parameters (FBD)", objective="To examine why..."
                        clean_title, embedded_objective = _split_title_and_objective(section_title)

                        # Fall back to separate Objective/Rationale column when present
                        # (backward-compat with older Excel files that still have the column)
                        correlation_value = embedded_objective

                        if correlation_value is None and correlation_col:
                            first_corr = (
                                section_group[correlation_col]
                                .dropna()
                                .astype(str)
                            )
                            if not first_corr.empty:
                                raw_corr = first_corr.iloc[0].strip()
                                correlation_value = _OBJECTIVE_PREFIX.sub('', raw_corr).strip() or None

                        # ----------------------------------------------------------
                        # Create section
                        # ----------------------------------------------------------
                        section_id = await conn.fetchval(
                            """
                            INSERT INTO rci_plan_section
                            (
                                rci_plan_id,
                                title,
                                correlation
                            )
                            VALUES ($1, $2, $3)
                            RETURNING id
                            """,
                            plan_id,
                            clean_title,
                            correlation_value,
                        )

                        sections_count += 1

                        # ----------------------------------------------------------
                        # Create tasks
                        # ----------------------------------------------------------
                        for _, row in section_group.iterrows():

                            task_description = str(
                                row[task_col]
                            ).strip()

                            if (
                                not task_description
                                or task_description.lower() == "nan"
                            ):
                                continue

                            await conn.execute(
                                """
                                INSERT INTO rci_plan_task
                                (
                                    rci_plan_section_id,
                                    description
                                )
                                VALUES ($1, $2)
                                """,
                                section_id,
                                task_description,
                            )

                            tasks_count += 1

        return ExcelUploadResponse(
            status="success",
            message=f"Successfully imported templates from {filename}",
            archetypes_processed=sorted(archetypes_processed),
            plans_created=plans_count,
            sections_created=sections_count,
            tasks_created=tasks_count,
        )

    except HTTPException:
        raise

    except Exception as e:
        logger.exception(
            "Failed to parse and upload RCI Plan templates"
        )

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to process upload: {str(e)}",
        )

    finally:
        await file.close()